// React/my-app/src/components/Product.tsx
import React, { useState } from "react";
import { IProduct } from "../models";

interface ProductProps{
    product:IProduct
}

export function Product(props:ProductProps){
    const [details,setDetails] = useState(false)

    

    return(
        <div className="border py-2 px-4 rounded flex flex-col items-center mb-2">
            Product : 
            {props.product.title}
            <img src={props.product.image} alt="123" className="w-1/6 " />
            <p>{props.product.title}</p>
            <span className="font-bold">{props.product.price}</span>
            <button 
            className="py-2 px-4 border bg-yellow-400"
            onClick={()=>setDetails(true)}
            >Show details
            </button>

{/* 43 minut */}
            {details && <div>
                <p>{props.product.description}</p>
            </div>}
            
        </div>
    )
}

// Angular/app/src/app/components/product/product.component.ts
import { Component, Input } from "@angular/core";
import { IProduct } from "src/app/models/product";

@Component({
    selector: 'app-product',
    templateUrl:'./product.component.html'
})

export class ProductComponent{
    title = 'app-product'

    @Input() product: IProduct

    details = false
}
<app-global-error></app-global-error>
<div class="py-4 px-6 border rounded flex items-center flex-col mb-2">
    <h2 class="mb-2 text-md text-center"> Назва продукту = {{ product.title }}</h2>
    <h2 >Ціна продукту = {{product.price | currency: 'UAH '}}</h2>
    <img [src]="product.image" [alt]="product.title" class="h-52 ">

    <button 
    class="border py-2 px-4 rounded "
    [ngClass]="{
        'bg-yellow-400': !details,
        'bg-blue-400': details 
    }"
    (click)="details = !details"
    >
    {{ details ? 'Hide' : 'Show' }} details
    </button>


    <p *ngIf="details">{{product.description}}</p>
    <p *ngIf="details">{{product.rating.rate | number: '1.2-4'}}</p>
  </div>
